names:
- speed_20
- speed_30
- speed_50
- speed_60
- speed_70
- speed_80
- speed_80_end
- speed_100
- speed_120
- no_overtaking
- no_overtaking_trucks
- priority_at_next_intersection
- priority_road
- give_way
- stop
- no_entry
- no_entry_trucks
- no_entry_one_way
- general_caution
- dangerous_curve_left
- dangerous_curve_right
- double_curve
- bumpy_road
- slippery_road
- road_narrows_right
- road_works
- traffic_signals
- pedestrians
- children_crossing
- bicycles_crossing
- ice_or_snow
- wild_animals_crossing
- end_of_all_speed_and_overtaking_limits
- turn_right_ahead
- turn_left_ahead
- ahead_only
- go_straight_or_right
- go_straight_or_left
- keep_right
- keep_left
- roundabout_mandatory
- end_of_no_overtaking
- end_of_no_overtaking_trucks
nc: 43
path: D:\rgznzuoye\new\data\baseline_lowlight_dataset
test: images/test
train: images/train
val: images/val
